#! /usr/bin/bash

source /exports/csce/datastore/geos/users/s1332488/minibonda/etc/profile.d/conda.sh

cd /disk/scratch/local.4/harry/DEM/DIM/

toNC=/home/s1332488/code/tandex/image_processing/export_netcdf.py
merge=/home/s1332488/code/tandex/image_processing/merge_datasets.py

conda activate pysnap

python $toNC

mv *.nc ../NC/
cd ../NC/

conda activate XR

python $merge
mkdir merged
mv *merged.nc merged/
mkdir separate
mv *.nc separate/


